import {
  AddressBookTabs,
  ArrowFatLineDown,
  ArrowFatLineUp,
  ArrowLeft,
  ArrowLineLeft,
  ArrowRight,
  CaretDoubleUp,
  CaretDown,
  CaretRight,
  ChartLine,
  ChartPieSlice,
  ChatCircleDots,
  ChatText,
  Check,
  CheckCircle,
  CheckFat,
  Dot,
  DotsSix,
  Envelope,
  EnvelopeOpen,
  Eyedropper,
  Fire,
  GearFine,
  Headset,
  HouseSimple,
  ImageSquare,
  Key,
  LockSimple,
  Minus,
  PauseCircle,
  Phone,
  PlayCircle,
  Plus,
  PlusCircle,
  Prohibit,
  RectangleDashed,
  RowsPlusBottom,
  SealCheck,
  SignOut,
  Spinner,
  StackPlus,
  Star,
  TextAa,
  TextAlignJustify,
  TextT,
  Trash,
  Tray,
  User,
  WarningCircle,
  X
} from '@phosphor-icons/react/dist/ssr';

export const ICON_MAP = {
  'address-book-tabs'  : AddressBookTabs,
  'arrow-fat-line-down': ArrowFatLineDown,
  'arrow-fat-line-up'  : ArrowFatLineUp,
  'arrow-left'         : ArrowLeft,
  'arrow-line-left'    : ArrowLineLeft,
  'arrow-right'        : ArrowRight,
  'caret-double-up'    : CaretDoubleUp,
  'caret-down'         : CaretDown,
  'caret-right'        : CaretRight,
  'chart-line'         : ChartLine,
  'chart-pie-slice'    : ChartPieSlice,
  'chat-circle-dots'   : ChatCircleDots,
  'chat-text'          : ChatText,
  'check-circle'       : CheckCircle,
  'check-fat'          : CheckFat,
  'dots-six'           : DotsSix,
  'envelope-open'      : EnvelopeOpen,
  'gear-fine'          : GearFine,
  'house-simple'       : HouseSimple,
  'image-square'       : ImageSquare,
  'lock-simple'        : LockSimple,
  'pause-circle'       : PauseCircle,
  'play-circle'        : PlayCircle,
  'plus-circle'        : PlusCircle,
  'rectangle-dashed'   : RectangleDashed,
  'rows-plus-bottom'   : RowsPlusBottom,
  'seal-check'         : SealCheck,
  'sign-out'           : SignOut,
  'stack-plus'         : StackPlus,
  'text-aa'            : TextAa,
  'text-t'             : TextT,
  'warning-circle'     : WarningCircle,
  burger               : TextAlignJustify,
  check                : Check,
  close                : X,
  dot                  : Dot,
  envelope             : Envelope,
  eyedropper           : Eyedropper,
  fire                 : Fire,
  headset              : Headset,
  key                  : Key,
  minus                : Minus,
  phone                : Phone,
  plus                 : Plus,
  prohibit             : Prohibit,
  spinner              : Spinner,
  star                 : Star,
  trash                : Trash,
  tray                 : Tray,
  user                 : User
} as const;

export type IIconName = keyof typeof ICON_MAP;
